name: pymc3-clone2
channels:
  - defaults
  - conda-forge
dependencies:
  - blas==1.0
  - ca-certificates==2020.6.20
  - icc_rt==2019.0.0
  - intel-openmp==2019.4
  - msys2-conda-epoch==20160418
  - pandoc==2.11.0.2
  - vs2015_runtime==14.16.27012
  - vswhere==2.7.1
  - winpty==0.4.3
  - m2w64-gmp==6.1.0
  - m2w64-headers-git==5.0.0.4636.c0ad18a
  - m2w64-isl==0.16.1
  - m2w64-libiconv==1.14
  - m2w64-libmangle-git==5.0.0.4509.2e5a9a2
  - m2w64-libwinpthread-git==5.0.0.4634.697f757
  - m2w64-make==4.1.2351.a80a8b8
  - m2w64-windows-default-manifest==6.4
  - mkl==2019.4
  - vc==14.1
  - vs2017_win-64==19.16.27038
  - bzip2==1.0.8
  - graphviz==2.38.0
  - icu==67.1
  - jpeg==9d
  - libblas==3.8.0
  - libclang==10.0.1
  - libgpuarray==0.7.6
  - libsodium==1.0.18
  - lz4-c==1.9.2
  - m2w64-crt-git==5.0.0.4636.2595836
  - m2w64-gcc-libs-core==5.3.0
  - m2w64-mpfr==3.1.4
  - m2w64-pkg-config==0.29.1
  - openssl==1.1.1h
  - python==3.6.11
  - sqlite==3.33.0
  - tk==8.6.10
  - xz==5.2.5
  - zlib==1.2.11
  - async_generator==1.1
  - attrs==20.2.0
  - backports==1
  - colorama==0.4.4
  - decorator==4.4.2
  - defusedxml==0.6.0
  - hdf4==4.2.13
  - idna==2.1
  - ipython_genutils==0.2.0
  - joblib==0.11
  - json5==0.9.5
  - krb5==1.17.1
  - libcblas==3.8.0
  - liblapack==3.8.0
  - libpng==1.6.37
  - libssh2==1.9.0
  - libtiff==4.1.0
  - m2w64-gcc-libgfortran==5.3.0
  - m2w64-mpc==1.0.3
  - m2w64-winpthreads-git==5.0.0.4634.697f757
  - nest-asyncio==1.4.1
  - olefile==0.46
  - pandocfilters==1.4.2
  - pickleshare==0.7.5
  - prometheus_client==0.8.0
  - pycparser==2.2
  - pyparsing==2.4.7
  - python-graphviz==0.14.2
  - python_abi==3.6
  - pytz==2020.1
  - qtpy==1.9.0
  - send2trash==1.5.0
  - simplegeneric==0.8.1
  - six==1.15.0
  - testpath==0.4.4
  - tqdm==4.50.2
  - webencodings==0.5.1
  - wheel==0.35.1
  - zeromq==4.3.2
  - zipp==3.3.1
  - zstd==1.4.5
  - certifi==2020.6.20
  - cffi==1.14.3
  - chardet==3.0.4
  - cycler==0.10.0
  - entrypoints==0.3
  - freetype==2.10.4
  - importlib-metadata==2.0.0
  - kiwisolver==1.2.0
  - libcurl==7.71.1
  - libpython==2
  - m2w64-gcc-libs==5.3.0
  - markupsafe==1.1.1
  - mistune==0.8.4
  - mkl-service==2.3.0
  - numpy==1.19.2
  - packaging==20.4
  - pyreadline==2.1
  - pyrsistent==0.17.3
  - python-dateutil==2.8.1
  - pywin32==228
  - pyzmq==19.0.2
  - qt==5.12.9
  - tornado==6.0.4
  - traitlets==4.3.3
  - win_inet_pton==1.1.0
  - wincertstore==0.2
  - argon2-cffi==20.1.0
  - brotlipy==0.7.0
  - cftime==1.2.1
  - cryptography==3.1.1
  - curl==7.71.1
  - hdf5==1.10.6
  - importlib_metadata==2.0.0
  - jupyter_core==4.6.3
  - m2w64-bzip2==1.0.6
  - m2w64-tools-git==5.0.0.4592.90b8472
  - mako==1.1.3
  - pandas==1.1.3
  - pillow==8.0.1
  - pyqt==5.12.3
  - pysocks==1.7.1
  - pywinpty==0.5.7
  - scipy==1.5.2
  - setuptools==49.6.0
  - backports.functools_lru_cache==1.6.1
  - bleach==3.2.1
  - h5py==2.10.0
  - jinja2==2.11.2
  - jsonschema==3.2.0
  - jupyter_client==6.1.7
  - libnetcdf==4.7.4
  - m2w64-zlib==1.2.8
  - matplotlib-base==3.3.2
  - patsy==0.5.1
  - pip==20.2.4
  - pygments==2.7.1
  - pygpu==0.7.6
  - pyopenssl==19.1.0
  - terminado==0.9.1
  - xarray==0.16.1
  - jupyterlab_pygments==0.1.2
  - m2w64-binutils==2.25.1
  - matplotlib==3.3.2
  - nbformat==5.0.8
  - netcdf4==1.5.4
  - theano==1.0.5
  - urllib3==1.25.11
  - wcwidth==0.2.5
  - arviz==0.10.0
  - m2w64-gcc==5.3.0
  - nbclient==0.5.1
  - prompt_toolkit==1.0.15
  - requests==2.24.0
  - ipython==5.8.0
  - m2w64-gcc-ada==5.3.0
  - m2w64-gcc-fortran==5.3.0
  - m2w64-gcc-objc==5.3.0
  - nbconvert==6.0.7
  - pymc3==3.8
  - ipykernel==5.3.4
  - m2w64-toolchain==5.3.0
  - jupyter_console==5.2.0
  - notebook==6.1.4
  - qtconsole==4.7.7
  - jupyterlab_server==1.2.0
  - widgetsnbextension==3.5.1
  - ipywidgets==7.5.1
  - jupyterlab==2.2.8
  - jupyter==1.0.0